AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  k8s-grader-api
  Sample SAM Template for k8s-grader-api
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
    MemorySize: 512
    Handler: app.lambda_handler
    Runtime: python3.11
    Architectures:
      - x86_64
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      
Resources:
  TestResultBucket:
    Type: AWS::S3::Bucket

  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "endpoint"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "EndpointIndex"
          KeySchema:
            - AttributeName: "endpoint"
              KeyType: "HASH"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "email"

  GameTaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: GameTaskTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "game"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "game"
          KeyType: "RANGE"

  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # TableName: SessionTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "game"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "game"
          KeyType: "RANGE"

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LibLayer
      Description: A layer for shared libraries
      ContentUri: layer
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: makefile # Required to have AWS SAM build this layer

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonLayer
      Description: Dependencies required for my Python lambdas
      ContentUri: common-layer/
      CompatibleRuntimes:
        - python3.11
      LicenseInfo: "Apache License 2.0"
    Metadata:
      BuildMethod: python3.11

  GameTaskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: game_task/
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Layers:
        - !Ref LibLayer
        - !Ref CommonLayer
      Environment:
        Variables:
          AccountTable: !Ref AccountTable
          SessionTable: !Ref SessionTable
          GameTaskTable: !Ref GameTaskTable
          TestResultBucket: !Ref TestResultBucket
      Events:
        GameTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /game-task
            Method: get

  GraderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: grader/
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Layers:
        - !Ref LibLayer
        - !Ref CommonLayer
      Environment:
        Variables:
          AccountTable: !Ref AccountTable
          SessionTable: !Ref SessionTable
          GameTaskTable: !Ref GameTaskTable
          TestResultBucket: !Ref TestResultBucket
      Events:
        GameTask:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /grader
            Method: get

  SaveK8sAccountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: save-k8s-account/
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Layers:
        - !Ref LibLayer
        - !Ref CommonLayer
      Environment:
        Variables:
          AccountTable: !Ref AccountTable
          SessionTable: !Ref SessionTable
          GameTaskTable: !Ref GameTaskTable
      Events:
        GameTaskGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-k8s-account
            Method: get
        GameTaskGetPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-k8s-account
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GameApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/game-task/"
  SaveK8sAccountApi:
    Description: "API Gateway endpoint URL for Prod stage for Save K8s Account function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save-k8s-account/"
  GraderApi:
    Description: "API Gateway endpoint URL for Prod stage for Grader function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/grader/?email=xxxx"
  AccountTable:
    Description: "Name of the AccountTable"
    Value: !Ref AccountTable
  GameTaskTable:
    Description: "Name of the GameTaskTable"
    Value: !Ref GameTaskTable
  SessionTable:
    Description: "Name of the SessionTable"
    Value: !Ref SessionTable
  TestResultBucket:
    Description: "Name of the TestResultBucket"
    Value: !Ref TestResultBucket
